name: example
description: "EXAMPLE"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_portal: ^1.1.4
  sm_modules:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
dependency_overrides:
  intl: ^0.17.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/no_available/no_checks.svg
    - assets/images/no_available/no_draws.svg
    - assets/images/no_available/no_issues.svg
    - assets/images/no_available/no_models.svg
    - assets/images/no_available/no_projects.svg