name: sm_modules
description: "SM UI kit"
version: 1.1.2
homepage: https://github.com/liis-dev-team/sm_modules.git
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

#  UI
  flutter_list_view: ^1.1.29
  pull_to_refresh: ^2.0.0
  flutter_portal: ^1.1.4
  intl: ^0.20.2
  flutter_localization: ^0.3.1
  flutter_svg: ^2.0.17

#  logic
  uuid: ^4.5.1
  flutter_bloc: ^9.0.0
  dart_date: ^1.4.0

#  generators
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  web: ^1.1.0
dependency_overrides:
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  intl: ^0.20.2
flutter:
  assets:
    - packages/sm_modules/assets/images/auth_back_cubes.png
    - packages/sm_modules/assets/images/logo.svg

  fonts:
    - family: AppIcons
      fonts:
        - asset: packages/sm_modules/assets/app_icons/sl/AppIcons.ttf
    - family: AppIconsExtra
      fonts:
        - asset: packages/sm_modules/assets/app_icons/extra/AppIconsExtra.ttf
    - family: AppIconsBold
      fonts:
        - asset: packages/sm_modules/assets/app_icons/sl/bold/AppIconsBold.ttf
    - family: AppIconsFill
      fonts:
        - asset: packages/sm_modules/assets/app_icons/sl/fill/AppIconsFill.ttf
    - family: NunitoSans-Black
      fonts:
        - asset: packages/sm_modules/assets/fonts/nunito_sans/NunitoSans-Black.ttf
    - family: NunitoSans-Bold
      fonts:
        - asset: packages/sm_modules/assets/fonts/nunito_sans/NunitoSans-Bold.ttf
    - family: NunitoSans-Regular
      fonts:
        - asset: packages/sm_modules/assets/fonts/nunito_sans/NunitoSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: packages/sm_modules/assets/fonts/roboto/Roboto-Regular.ttf