name: sm_modules
description: "SM UI kit"
version: 1.0.0
homepage: https://github.com/liis-dev-team/sm_modules.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
#  UI
  flutter_list_view: ^1.1.22
  pull_to_refresh: ^2.0.0
  flutter_portal: ^1.1.4
  intl: ^0.18.1
  flutter_localization: ^0.1.14
  calendar_date_picker2:
    path: ./lib/packages/calendar_date_picker2

#  logic
  uuid: ^4.1.0
  flutter_bloc: ^8.1.2
  dart_date: ^1.2.2

#  generators
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/app_icons/sl/AppIcons.ttf
    - family: AppIconsExtra
      fonts:
        - asset: assets/app_icons/extra/AppIconsExtra.ttf
    - family: AppIconsBold
      fonts:
        - asset: assets/app_icons/sl/bold/AppIconsBold.ttf
    - family: AppIconsFill
      fonts:
        - asset: assets/app_icons/sl/fill/AppIconsFill.ttf
    - family: NunitoSans-Black
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans-Black.ttf
    - family: NunitoSans-Bold
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans-Bold.ttf
    - family: NunitoSans-Regular
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf