name: sm_modules
description: "SM UI kit"
version: 1.0.0
homepage: https://github.com/liis-dev-team/sm_modules.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
#  UI
  flutter_list_view: ^1.1.22
  pull_to_refresh: ^2.0.0
  flutter_portal: ^1.1.4
  intl: ^0.18.1
  flutter_localization: ^0.1.14
  calendar_date_picker2:
    path: ./lib/packages/calendar_date_picker2

#  logic
  uuid: ^4.1.0
  flutter_bloc: ^8.1.2
  dart_date: ^1.2.2

#  generators
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:
